#!/usr/bin/env python3
"""Generate a self-contained velocity report HTML with embedded metrics data.

Usage:
    python3 .claude/scripts/velocity-report.py .claude/metrics.jsonl
    python3 .claude/scripts/velocity-report.py .claude/metrics.jsonl -o velocity-2026-03-30.html
    python3 .claude/scripts/velocity-report.py .claude/metrics.jsonl > report.html

The output is a single HTML file with all chart data embedded inline.
No file picker needed — just open in any browser.
"""
import json
import sys
import os
import argparse
from datetime import datetime


def load_metrics(path):
    """Load metrics.jsonl and return as JSON array string."""
    records = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return records


def load_template():
    """Load velocity.html template from the same directory."""
    script_dir = os.path.dirname(os.path.abspath(__file__))
    template_path = os.path.join(script_dir, '..', 'velocity.html')
    if not os.path.exists(template_path):
        print(f"Error: velocity.html not found at {template_path}", file=sys.stderr)
        sys.exit(1)
    with open(template_path) as f:
        return f.read()


def embed_data(template, records):
    """Replace the file picker with embedded data and auto-render."""
    data_json = json.dumps(records, separators=(',', ':'))
    count = len(records)
    beads = len(set(r.get('bead_id', '') for r in records if r.get('record_type') != 'session_time'))
    sessions = len(set(r.get('session_id', '') for r in records))
    generated = datetime.now().strftime('%Y-%m-%d %H:%M')

    # Replace the file picker section with a hidden div
    old_load = '''<div id="load-section">
  <p style="color:var(--muted);font-size:16px;margin-bottom:16px">Load metrics data to begin</p>
  <label>Select metrics.jsonl<input type="file" id="file-input" accept=".jsonl"></label>
  <p style="color:var(--muted);font-size:12px;margin-top:12px">File: <code>.claude/metrics.jsonl</code></p>
</div>'''
    new_load = f'<div id="load-section" style="display:none"></div>'
    template = template.replace(old_load, new_load)

    # Make dashboard visible by default — remove both inline style and CSS rule
    template = template.replace(
        '<div id="dashboard" style="display:none">',
        '<div id="dashboard">'
    )
    template = template.replace(
        '#dashboard{display:none}',
        '#dashboard{display:block}'
    )

    # Update subtitle
    template = template.replace(
        'Mission Control — Self-reflection dashboard for Agentic Agile development',
        f'Mission Control — Velocity Report generated {generated}'
    )

    # Replace the file loader JS with embedded data + auto-render
    old_loader = '''document.getElementById('file-input').addEventListener('change', function(e) {
  const file = e.target.files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = function(ev) {
    const lines = ev.target.result.trim().split('\\n');
    ALL_DATA = lines.map(l => { try { return JSON.parse(l); } catch(e) { return null; } }).filter(Boolean);
    buildSprints();
    initSlider();
    render();
    document.getElementById('load-section').style.display = 'none';
    document.getElementById('dashboard').style.display = 'block';
  };
  reader.readAsText(file);
});'''

    new_loader = f'''// Embedded data — generated by velocity-report.py
ALL_DATA = {data_json};'''

    # Add auto-render at the end of the main script block (last </script>)
    # Use requestAnimationFrame to ensure layout is computed before Chart.js renders
    last_script_idx = template.rfind('</script>')
    if last_script_idx != -1:
        template = (
            template[:last_script_idx]
            + '\n// Auto-render embedded data — delay until layout is ready\n'
            + 'window.addEventListener("load", function() {\n'
            + '  buildSprints();\n'
            + '  initSlider();\n'
            + '  render();\n'
            + '});\n'
            + template[last_script_idx:]
        )

    template = template.replace(old_loader, new_loader)

    return template


def main():
    parser = argparse.ArgumentParser(
        description='Generate self-contained velocity report HTML'
    )
    parser.add_argument('metrics', help='Path to metrics.jsonl')
    parser.add_argument('-o', '--output', help='Output file (default: stdout)')
    args = parser.parse_args()

    if not os.path.exists(args.metrics):
        print(f"Error: {args.metrics} not found", file=sys.stderr)
        sys.exit(1)

    records = load_metrics(args.metrics)
    template = load_template()
    html = embed_data(template, records)

    if args.output:
        with open(args.output, 'w') as f:
            f.write(html)
        beads = len(set(r.get('bead_id', '') for r in records if r.get('record_type') != 'session_time'))
        print(f"Generated {args.output} ({len(records)} records, {beads} beads)", file=sys.stderr)
    else:
        print(html)


if __name__ == '__main__':
    main()
